//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGO_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int Id { get; set; }
        public int IdProveedor { get; set; }
        public int IdTipoPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual TiposPago TiposPago { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
