//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGO_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdProducto { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public decimal Cantidad { get; set; }
        public int DescuentaStock { get; set; }
    }
}
