//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGO_Ventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.VentasXDetalles = new HashSet<VentasXDetalles>();
        }
    
        public int Id { get; set; }
        public string CodBarra { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdRubro { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> PrecioL1 { get; set; }
        public Nullable<decimal> PrecioL2 { get; set; }
        public Nullable<decimal> PrecioL3 { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public decimal StockMinimo { get; set; }
        public Nullable<decimal> IVAVenta { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual Rubros Rubros { get; set; }
        public virtual Unidades Unidades { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasXDetalles> VentasXDetalles { get; set; }
    }
}
